### PR TITLE
Casper Mountain Complex

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Balance:
 - Enclave given four additional roles.
    - Enclave Pilot. Two slots. They are now the exclusive source of flight.
    - Enclave Bunker Duty. Two slots. These are non-combatant roles, and utilize a new flag that'll be explained in a moment.
 - Brotherhood given six additional slots.
    - Off-Duty. Six slots. These are non-combatant roles, and utilize a new flag that'll be explained in a moment.
 - Vex slots raised to two.
 - Vex provided with terrifying presence.
 - NCR HT slots raised to two, post nerf.
 - NCR Representative given Lifegiver (increase to max HP), Self Aware (able to see damage without health scanner) and Terrifying Presence.
- - -
Map:
 - Enclave removed from the primary map and given their own unique Z, to prevent meta rushing from both sides, and to enforce usage of the Vertibird.
 - The NCR's mine is now vastly expanded, almost doubling in size.
- - -
Other:
 - A new flag for roles, known as the 'Roleplay Flag', is provided for jobs that aren't permitted to participate in offensive raids. A myriad of pre-existing roles are effected by it.
    - Enclave Pilot Officer
    - Enclave Bunker Duty
    - BoS Off-Duty
    - Baron / Elder
    - ALL Follower Roles
    - Legion Orator
    - Legion Slave Master
    - Legion Immune
    - Legion Auxilia
    - Legion Forgemaster
    - Legion Slaves
    - NCR Drill Sergeant
    - NCR  Representative
    - NCR LO
    - NCR Rear Echelon
    - NCR Military Police
    - NCR Medical Officer
- - -

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Whoops. Didn't mean to create this just yet.

**Comment by ProbablyCarl** [comment]
image

**Review by ExoticJazz — APPROVED** [review]
enclave bias

**Comment by UntoldTactics** [comment]
snowvenrock

**Pull request merged**
