### PR TITLE
Black-backed jackal sprites

### PR DESCRIPTION
**Pull request by Mocha-Not-Latte**
## About The Pull Request
Adds jackal back-markings and a new tail
unknown

## Why It's Good For The Game
It gives me snowflake look because noone else is going to use these :)

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new sprites
/:cl:

### CODE REVIEW

**Review by PolymorphBlue — APPROVED** [review]
Looks good!

**Comment by ProbablyCarl** [comment]
Good to go?

**Comment by Mocha-Not-Latte** [comment]
> Good to go?

yep

**Comment by Mocha-Not-Latte** [comment]
I hate linters I hate linters

**Comment by PolymorphBlue** [comment]
>missing newlines detected  

Sorry =<  It's probably for the best we maintain them, though.  If you could fix that, please?

**Pull request merged**
