### PR TITLE
[Do Not Merge Yet] Khan armor backend, sprites, and buff to armor plates.

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
Added a versatile armor set for Khanate Citizens (a NYI selectable loadout for Bighorn residents. Will also be purchasable at a vendor in the Khanate fortress barracks) whose largest advantage is its expanded storage, as well as an inferior version lacking the Khanate back patch, which is intended for Khanate Prospects (a NYI Wastelander loadout).

Also adds Mangudai armor and helmet, which are decent all-around with some pretty good protection against low levels of radiation.

## Why It's Good For The Game
The armor is a planned feature, and armor plates kinda suck right now, making it so you always want to find the upgradable armor with the highest base stats rather than using the plates to make your favorite one meaningfully viable.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.
Project Checklist
- [x] Mangudai Armor & Helmet Sprited
- [x] Mangudai Armor & Helmet Coded
- [x] Mangudai Loadouts & Starting Gear Updated
- [x] Kipchak Armor & Helmet Sprited
- [x] Kipchak Armor & Helmet Coded
- [x] Kipchak Loadouts & Starting Gear Updated
- [x] Khorchin Armor & Helmet Sprited
- [x] Khorchin Armor & Helmet Coded
- [x] Khorchin Loadouts & Starting Gear Updated
- [x] Kheshig Armor & Helmet Sprited
- [x] Kheshig Armor & Helmet Coded
- [x] Kheshig Loadouts & Starting Gear Updated
- [x] Citizen and Prospect Armor Sprited
- [x] Citizen and Prospect Armor Coded
- [x] Citizen Starting Gear Updated

## Changelog

:cl:
imageadd: added prospect and citizen armor for Khan use, as well as mangudai armor and helmet
add: the aforementioned Mangudai armor
balance: buffs armor plate bonus from 2 per plate to 5.
code: Changed an unused version of the khan jacket in the code into the prospect armor. Made the khan citizen armor a superior subtype of that.
/:cl:

### CODE REVIEW

**Comment by hackerjsimon** [comment]
Damn the armor values are a little unbalanced, not to mention making the armor plates( which in my opinion should be removed) even stronger [+25 on armor]; all armor in the game would be the same value as PA... Don't ever change that value either just revert the plate commit. The whole point of the armor plating was to slow the game progression for TDM on wasteland, and that isn't a problem here so it could simply be removed altogether.

Khanate citizen armor
[35/35/30]
Khanate Mangudai armor
[45/45/35] --> which can be plated and according to this code would be [70/70/35] literally the rarest armor in the game strong FOR A ROLE WITH MULTIPLE OPENINGS.



You spawn with this armor too... on a neutral faction. The Mangudai armor values are already the same as Reinforced combat armor which you get from dungeons. Considering the khan are low-class thugs in fallout it'd be better to have distinct armor values like 45/35(Vice Versa) with normal plates -> 55/35. This whole paragraph is mainly due to having such strong armor with zero slowdown.

note: I am aware other roles have strong armors, but the issue lies in quantity, especially where only a single player has access versus multiple. At the end of the day, I'm just giving my 2 cents.

**Comment by DerFlammenwerfer** [comment]
> Damn the armor values are a little unbalanced, not to mention making the armor plates( which in my opinion should be removed) even stronger [+25 on armor]; all armor in the game would be the same value as PA... Don't ever change that value either just revert the plate commit. The whole point of the armor plating was to slow the game progression for TDM on wasteland, and that isn't a problem here so it could simply be removed altogether.
> 
> Khanate citizen armor [35/35/30] Khanate Mangudai armor [45/45/35] --> which can be plated and according to this code would be [70/70/35] literally the same stats as the rarest armor in the game, and this is **FOR A ROLE WITH MULTIPLE OPENINGS.**
> 
> You spawn with this armor too... on a neutral faction. The Mangudai armor values are already the same as Reinforced combat armor which you get from dungeons. Considering the khan are low-class thugs in fallout it'd be better to have distinct armor values like 45/35(Vice Versa) with normal plates -> 55/35. This whole paragraph is mainly due to having such strong armor with zero slowdown.
> 
> note: I am aware other roles have strong armors, but the issue lies in quantity, especially where only a single player has access versus multiple. At the end of the day, I'm just giving my 2 cents.

All of this is going to be coinciding with a rework to movement speed, gunplay, and standardization of damage by caliber, with some adjustments based on the features of guns using those calibers.

**Comment by ExoticJazz** [comment]
Any progress on pushing this? It has been 3 months and I would preferably have everything in before the great rebalancing.

**Comment by ProbablyCarl** [comment]
Safe to assume this is abandoned?

**Comment by ProbablyCarl** [comment]
Closing this for now. Contact me if you wish it to be reopened, as I'm assuming it's abandoned.

**Pull request closed without merging**
