### PR TITLE
Area Fixes and Correcting Missing Turfs (RockSprings)

### PR DESCRIPTION
**Pull request by SigholtStarsong**
## About The Pull Request

This PR contains a bevy of fixes to the RockSprings maps to make it more consistent with other maps with two-level buildings. This should fix weather happening indoors in the Legion camp and assorted buildings around Rock Springs. this also removes some forgotten (read: broken) turf types from the north-west, collapsed corner of the prison.

## Why It's Good For The Game

Mapping fixes are mildly important.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: two new riveted/boss subtypes to better contain particularly dangerous fauna and help the prison survive the Powder Ganger lifestyle.
del: Removed a mirror floating in the void on Upper
fix: Rezoned the buildings on the Upper z-level to appropriate indoor types.
fix: Rezoned legion buildings to appropriate Legion area type.
fix: creates a 'weakened prison wall' section in the prison for alternative entrances.
/:cl:

### CODE REVIEW

**Comment by SigholtStarsong** [comment]
I swear, this thing just doesn't like me. I don't have the crayons to hash this out immediately, but I'll take another stab at it later today.

**Comment by SigholtStarsong** [comment]
Do not merge immediately, Emergency fix for the prison incoming.

**Comment by SigholtStarsong** [comment]
Emergency fix applied. If it passes, it should be ready to merge.

**Comment by out-of-phaze** [comment]
There's some weird extra desert turfs on the upper level of RockSprings.

**Comment by SigholtStarsong** [comment]
This PR is catastrophically fucked.

**Pull request closed without merging**
