### PR TITLE
Buffs Large Calibre Munitions - .50 / 12.7

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Balance:
 - AMR is now semi-automatic for those that have the fast-pump trait, which is given automatically to the Veteran Ranger.
 - AMR damage up from fifty(50) to sixty(60).
 - AMR penetration bonus up from 0.6 to 1.
 - Legion Explorer has lost Insane Aim, making it exclusive to the singular Venator and Veteran Ranger roles.
 - HMG round damage up from five(5) to fifteen(15).
 - Standard heavy munitions (.50 / 12.7) given a wound bonus of twenty(20), and a bare wound bonus of sixty(60)
- - -

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
How the blood change mingled its way in? I've no clue. Identical, however, to how it was prior.

**Comment by Spc-Dragonfruits** [comment]
Consider lowering the AMR's penetration to 0.7 from 1, since it starts stepping on the Gauss Rifle's role as a proper anti-everything sniper rifle (0.9 AP)

**Comment by ProbablyCarl** [comment]
> Consider lowering the AMR's penetration to 0.7 from 1, since it starts stepping on the Gauss Rifle's role as a proper anti-everything sniper rifle (0.9 AP)

The Gauss Rifle is significantly easier to get ammunition for, unless I'm mistaken, and the AMR is far harder to obtain outside of RNG drops. Gauss Rifles can be mass produced, as can AMRs I suppose, but the former is more likely to be used in nearly all circumstances.

**Review by PolymorphBlue — APPROVED** [review]
Looks fine.

**Pull request merged**
