### PR TITLE
Prison Fix, Cheese Fix, NCR Dress Wardrobes, Museum Tweak

### PR DESCRIPTION
**Pull request by SigholtStarsong**
## About The Pull Request
This PR fixes some incorrect walls in the Prison and nerfs the loot available there, fixes two notable cheese routes in Rock Springs and Pahrump, adds in a set of dress uniform wardrobes just south of the NCR briefing room, and adds some toys for the Museum giftshop to storage.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Autoylathe to Museum backroom
add: Pre-placed hostile armored ghoul spawns to supplement ghoul numbers and make the museum less cheesasble.
add: Toys to the Museum
add: NCR dress uniforms in a series of cabinets in a room to the south of the Briefing Room
add: Adds a chew-chew to the deserted enclave bunker
del: Removes
tweak: Removed Elite Riot Gear from the prison dungeon, and adds Tier 4 armor spawn & blueprint to compensate in dungeon
tweak: adjusts a few rock walls to be dense rock, and removes cheese possibility.

/:cl:

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Looks like there's a number of erroneously placed things here?
Stairs in Warren, for example.

**Review by ExoticJazz — APPROVED** [review]
First time contributor! 
👏 🎊 

Butt yeah, need those fixes before it's possible to merge.

**Comment by SigholtStarsong** [comment]
That's strange. I never touched stairs in Warren. I'll review it when I get
home. DNM until then.

**Comment by SigholtStarsong** [comment]
Strange tiles removed. No idea how either of those got there, since I didn't touch stairs and didn't even open the Dungeons.dmm in this gothrough.

**Pull request merged**
