### PR TITLE
xenobio nerf, food prefs, blood compatibility

### PR DESCRIPTION
**Pull request by Ducky-Momo**
## About The Pull Request

fixes enclave scientist ammo spawn (im retarded and gave it the wrong ammo type after it was already fixed cause i got it mixed up), changes bug and lizard blood to be a universal recipient due to the death sentence that bloodloss as a bug/lizard was, comments out certain overpowered/too strong xenobiological things, and tweaks species food preferences to allow more RP-oriented tastes rather than mechanically enforced
## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: gives enclave scientists correct ammo upon spawn (im retarded)
tweak: changes some species food dislikes to basically allow players to decide
balance: disables certain overpowered/abusable xenobiology cores/extracts
balance: changes lizard and bug blood to be universal recipients like AB+
/:cl:

### CODE REVIEW

**Comment by Nep993** [comment]
What changes does it make to xenobio? You've left out all detail.

**Comment by ProbablyCarl** [comment]
Changelog, I beg ye.

**Comment by DiscordWizard** [comment]
Rad energy weapon buff aside, can't say I see this as a good change, If I'm fighting against the enclave I want to fight against mad scientists using every tool at their disposal. Moderate abuse, don't outright remove the more fun parts of it.

**Comment by IrkallaEpsilon** [comment]
Right waited a good 8 hours. This is going to be long.

Changes what this exactly does:

Haphazardly removes:
- Emergency teleport on crit extract which more or less is only a problem if people start invading Casper Mountain, otherwise the person is effectively defeated as the crit teleport immediately works even if other factors (medicine) are in play that could push something out of crit rapidly. It takes a good 2-3 mins to get out of Casper from enclave base.
-  Disables the actually balanced teleport in form of the chilled bluespace extract. It requires to hit a user and then use it in hand. It teleports anyone hit after a windup to the guy with the extract. It has a windup of a few seconds and requires the person being teleported to not resist in any form. If enclave wanted to use that somebody at the base had to use it. Have seen it been used once. Anyone can resist out of the teleport.
-  Disables red slime potions entirely: Red slime potions and that other red slime core allow no slowdown. This is problematic since it applies to weapon slowdowns as well. Instead of full removal it should be just removed from weapons so one doesnt wind up with full speed gatling lasers.
-  Disables the regenerative bluespace extract which is  A) used for emergency teleport B) as a sort of recall potion C) used for abductions. Instead of fixing it by giving it the same kind of windup the chilled bluespace extract has it got its function blanket removed
- Sepia Rewind Camera. Really..? When was this actually used? For those unaware what it does: Take an image of yourself or any other person. The location is saved. After 10 seconds it plays Youtube Rewind 2018 and puts the person on the image back into the state they were 10 seconds ago. It repeats this process one more time for a total of 2. Has uses in combat but its still very gimmicky to use. If the person dies during the 10 second rewind they won't get revived. Other gimmicky applications involve: Rewinding rads in the reactor. Rewinding FEV infections if you drink it AFTER taking the image and dont get simple mobbed.
- Missed the actually only very problematic extract that used to be very present on TG, not for its primary intent but rather on how it works with some side effects, I am not going to mention which one.

Why haphazardly? You still get the cores when trying the recipes by the looks of it. They just don't have any function, aka they make you waste resources. Instead of simply giving the same 5 second or what windup from chilling so teleports arent an instant use (or heck even just not let them be used instantly on other people) it blanket removes one of the tools that so far prevented enclaves from being forced to either A) stay in the bunker B) go out anyways and get validcoptered the moment somebody decides to 'meta' through a disguise by everyone and their ERP partner in the wasteland C) Use far more lethal and far more bullshit alternatives to get out.  If people dont want clavies to port out the moment its a sudden 20 v 1 perhaps they shouldn't gang up on them the moment they show up. Every SINGLE encounter with clavies resulted in everyone grabbing whatever bunker loot they got amongst whatever other shit they got and converge on them. Every single "capture" of a clavie so far resulted in full RR bar one very lucky instance where NCR was occupied with an event. Bodies are being hidden, seen gib attempts. Heck even seen a chunk of guys camp casper entrance after clavies got called out in the field. 

What 'those evil round ruining enclave players' do: Walk into the wasteland disguised. Do shady trades with few people that actually care to engage with them. Arm tribals with advanced weaponry and augments. Be some cryptid. Abduct people that actually care for that stuff. Pretend to be G-Man from half life. Shitpost on comms as Highland Rangers and sow confusion. Actually try to stick to agreements for longer than just a day or two.  They only get involved in actual PvP if theres a very good reason (aka coders want to test the mortar, some guy in Casper). How does any of that warrant removal of "OP bullshit teleports" that are kind of required the moment somebody decides to become Uland 'Valid' Hunt, professional hunter of valids and you don't want to mass cas the validseeking missiles? 

Just give the wind up from chilled bluespace to the other teleports (and to the rewind cam too, not like that anybody ever used it). Heck have the red extract just be applied to armor. 

Other: 
- Buff some beam weapon to do more rad damage (200 to 250), probs that gamma gun (which in on itself gets ditched for AEP 7 roundstart since its so awfully gimmicky. This is nowhere documented.
- Food prefs are now more prefs than hard mechanical reqs.

**Pull request closed without merging**
