### PR TITLE
Adds 'Desert Warrior' loadout for NCR trooper

### PR DESCRIPTION
**Pull request by Troontjelolo**
### The Gist Of It
It's trekking but for NCR troopers. Downside is you only get an M1911 and a machete, along with shittier armour. At least you have melee: 30. Another thing is your helmet, mainly, your lack of one. Instead, you get a headscarf which looks cool but is mere cloth; it will not stop bullets.

### The Looks Of It
image

### The Why Of It

https://user-images.githubusercontent.com/56892466/202823764-aa945d49-f226-40d3-8c65-7893224c6f29.mp4

**DO NOT MERGE THIS PLEASE UNTIL I CAN TEST IT. THIS IS LITERALLY MY FIRST PR EVER SO SHIT IS LIKELY BROKEN. ALTERNATIVELY, SOMEONE ELSE CAN TEST IT IF THEY WANT TO WINK WINK NUDGE NUDGE**

### CODE REVIEW

**Comment by neri-ventado** [comment]
holy shit this is ultra based

**Comment by Troontjelolo** [comment]
image
PR so Arab nationalist that Bashar-al Assad starts playing

**Comment by Troontjelolo** [comment]
after some testing i've come to two conclusions:
1. giving the armour the ability to be plated could help make this the _true_ melee option (HT, eat your heart out)
2. icon sprite for the headscarf is broken. womp womp - gotta fix that

**Comment by Troontjelolo** [comment]
image
god, california and kimball

**Comment by Troontjelolo** [comment]
oh also storing shit still doesnt work. womp womp

**Comment by Troontjelolo** [comment]
_Both the sprite and plates and storage still doesnt work. why, has it ever?_
image

**Comment by Troontjelolo** [comment]
im going to give up for now. i'll try again in a week or so. i need to take a different approach to this. this has been a learning experience, at least.

**Pull request closed without merging**
