### PR TITLE
Minor minigun balance changes

### PR DESCRIPTION
**Pull request by ThatGuyFromThatPlace**
## About The Pull Request

I've consistently seen a number of people refer to the minigun as a "Noob trap" and generally say that it's a poor gun. While I've had success with it in PvE, I've noticed in PvP, it tends to fall flat on its face unless you use it as a shotgun to surprise people in CQC (Which can be accomplished better with say, an actual shotgun, like the city killer, which would allow you to actually make chase and do follow up shots). Anyone who knows what they're up against, and is prepared can generally abuse the slowdown to kill you with ease, or run away with ease

While it wouldn't make sense to completely take away all weaknesses from it, I figured I'd see about giving a very minor change to the two points people tend to mention most in regards to its balance.

_I'm hoping these changes are light-handed, as, I don't intend to remove its weaknesses, but, simply lessen them._

Compared to the laser minigun, the ballistic minigun has double the slowdown, more spread, and, can't easily reload in the field due to the inability to carry around ammo boxes in a belt

The laser minigun, aside from the heat diffusion, is generally better than the minigun to the point of being a straight upgrade, so, I've left it untouched.

## Why It's Good For The Game

Makes a weapon generally considered weak, less weak, without trying to remove its weaknesses or make it overpowered

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
(Before > After, unlike Dragonfruits backwards stuff, smh)
CZ53:
Slowdown: 2 > 1.8
Heat diffusion: 2.5 > 3

### CODE REVIEW

**Comment by Nep993** [comment]
oh baby that's a lotta failed checks, did you try and compile this?

**Comment by ThatGuyFromThatPlace** [comment]
> oh baby that's a lotta failed checks, did you try and compile this?

Forgot to update the fork before throwing the PR up is all. That fixed it

**Comment by SigholtStarsong** [comment]
Please put all the changes in a changelog!

**Comment by ThatGuyFromThatPlace** [comment]
> Please put all the changes in a changelog!

The PR creation format specifically said that, for small PRs you don't need to fill the changelog though?

**Pull request merged**
