### PR TITLE
Remove AVX and AVX2 from auxmos for better compat

### PR DESCRIPTION
**Pull request by out-of-phaze**
## About The Pull Request
The auxmos binary in the repo included support for AVX and AVX2 instruction sets, which has been giving some users on older/lower-end hardware issues when they try to host the server locally. This will hopefully fix that.

## Why It's Good For The Game
Helps people host test servers on old, moldy potatoes.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Allfd** [comment]
Did you run this in a profiler?  Turning off AVX  can have a massive performance hit.

**Comment by Allfd** [comment]
This is the type of thing that gets lost to the sands of time.  At somepoint someone may want to run a server on windows as a downstream, and it will have an intentionally crippled library.

Best practice would be to keep the upstream file in-place, and document the location of an alternate file if you have very old hardware in the readme.

**Comment by out-of-phaze** [comment]
> This is the type of thing that gets lost to the sands of time. At somepoint someone may want to run a server on windows as a downstream, and it will have an intentionally crippled library.
> 
> Best practice would be to keep the upstream file in-place, and document the location of an alternate file if you have very old hardware in the readme.

No. Thanks for the feedback, though. Frankly, if our contributors were more competent, I'd have no problem just not including a binary in the repo at all.

**Comment by PolymorphBlue** [comment]
I can see both sides of the argument.   This .dll here is just to simply setting up a local server - running the TGS scripts actually acquires the proper version of the library.

I don't think it's a bad thing to expect a checkout to actually start when you compile it (as to including the file), but I also think it should for this use case include as many people as possible.

**Pull request merged**
