### PR TITLE
Reattempts prison repairs

### PR DESCRIPTION
**Pull request by SigholtStarsong**
## About The Pull Request

This should resolve a number of problems with the prison and resolve at least one runtime.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: one new holofloor subtype, and a number of new instances of riveted walls to increase blast resilience of the prison.
tweak: Removes Supermutant Behemoth, replaces him with _three_ "strong-looking abominations" and centaurs in a unique faction.
del: Removed alien corpse spawner to resolve a runtime.
/:cl:

### CODE REVIEW

**Comment by SigholtStarsong** [comment]
If everything passes, this will be fine to merge in.

**Comment by ProbablyCarl** [comment]
Replace the holofloor subtype with an indestructible subtype.
Additionally, abominations might be far too powerful. Are they the same from 2016? I've not seen them used properly in some time.

**Comment by SigholtStarsong** [comment]
> Replace the holofloor subtype with an indestructible subtype. Additionally, abominations might be far too powerful. Are they the same from 2016? I've not seen them used properly in some time.

After testing with the Abominations, they're hard to kill but aren't impossible. They also take a few hits to actually drop someone in Power Armor.

The degree of difficulty for this sub-dungeon either has to remain very high or I need to severely adjust down the loot available in it.

**Comment by ProbablyCarl** [comment]
Fair enough. If you've tested it, no issue then. Wouldn't use holoflooring, though.

**Comment by SigholtStarsong** [comment]
Adjustments met. Ready for review again, @ProbablyCarl

**Review by ProbablyCarl — APPROVED** [review]

**Pull request merged**
