### PR TITLE
fluff for shark fox

### PR DESCRIPTION
**Pull request by Moribun**
told him I'd do it for him

just a fluff set for him based off an IC promotion from awhile ago, told him I'd drop it for him

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Rayfod** [comment]
Plasma is enclave only.
You are giving them a trait they are never supposed to have and should be earned in-game.

**Comment by Moribun** [comment]
was given the pistol during an in game event as a prize over the enclave from what I am told and has crystal mutations on hand to justify the book. apparently this was a long time coming and no one got around too it. I offered to do it so I did. carl can judge and speak with them weather it is valid or not...dont shoot the messenger as they say

**Comment by Hyro-Fox** [comment]
Glock 86A Plasma Pistol is a rare, yet obtainable plasma weapon for either Enclave or BoS to have it. Canonically, Hyro received it through promotion and I have print of the loadout. Unforunately, not from in-game exchange. It should bring the attention of Carl to this matter and have him to make a choice.

**Comment by Hyro-Fox** [comment]
A plasma pistol can be obtained by playing keeper and choosing administrator gear. So it is not primarily or totally exclusive to Enclave.

**Comment by projectkepler-ru** [comment]
I have my own loadout with the golden sniper rifle that's. for the most part, a thing unique to my kitsune and is very rarely used by anyone else, if at all.

Has to say, I think so long as it's not abused it should be mostly fine.

**Comment by ProbablyCarl** [comment]
> A plasma pistol can be obtained by playing keeper and choosing administrator gear. So it is not primarily or totally exclusive to Enclave.

That's oversight, left in by me after minor discussion.
Plasma is near exclusive, for good reason, to Enclave.

To give you a plasma glock would be an absurdly powerful item. At the very least, nerf it.

**Comment by Moribun** [comment]
there....can I go now?

**Pull request closed without merging**
