### PR TITLE
Topside BoS Entrace Overhall Ft. No Man's Land fix

### PR DESCRIPTION
**Pull request by Kavrick**
So the aim of this overhaul is simple, to add somewhere an entrance to the BoS base that is topside, allowing for actual raids and interactivity outside of having a teleporting elevator. The Mess hall, medical bay, meeting room, communications room and Baron's Office has been moved upside, and I have added a tunnel that goes from the west side of the nightstalker forest into the base, with working shutters. I've tested pretty much everything, as far as I know it should all work fine.

I'll be around and happy to be pinged for feedback and changes in the future, as this is my first time doing such a big mapping change. Screenshots to follow

P.S, I added fixed ladders to the no-man's land on both sides.
StrongDMM_rgTyHxKoJb
StrongDMM_VSvUfywRm9

### CODE REVIEW

**Comment by Kavrick** [comment]
Updated Images for Clarity:

**New Bunker**
StrongDMM_rouL1dyFuP

**Ground Floor Entrance**
StrongDMM_eh8NJ0g2u0

**Second Floor Entrance**
StrongDMM_dkX5hvAyq0

**Comment by SigholtStarsong** [comment]
Can you actually remove the No Mans Land ladders for now or place appropriate ladders in respective faction areas? The BoS are the only group with access to the area currently.

**Comment by Rayfod** [comment]
Skærmbillede 2022-09-14 061115
No

**Comment by Rayfod** [comment]
Skærmbillede 2022-09-14 061833
They can mine to here and thermite the walls to completely remove all the brotherhood of steel defenses

**Comment by Kavrick** [comment]
> Can you actually remove the No Mans Land ladders for now or place appropriate ladders in respective faction areas? The BoS are the only group with access to the area currently.

The respective ladders are in the right places. 
StrongDMM_WOa88hRFir
StrongDMM_M8dIT46N9g

**Comment by Kavrick** [comment]
Dont merge yet, trying to figure this stuff out, I hate you carl.

**Review by ExoticJazz — APPROVED** [review]

**Pull request closed without merging**
