### PR TITLE
Barbed Wire Nerfs

### PR DESCRIPTION
**Pull request by Kavrick**
Basically just making it so barbed wire is made with titanium rather than metal rods, making it far less spammable.

### CODE REVIEW

**Comment by Kavrick** [comment]
no idea how it failed to compile maps when this doesn't touch map files.

**Comment by ProbablyCarl** [comment]
Not sure how I feel about this.
Why make it more difficult to make? Doesn't touch anything else except that?
It just turns it into CBT.

**Comment by ProbablyCarl** [comment]
Also, check the files changed. It shows the exact issue.

**Comment by SigholtStarsong** [comment]
> Not sure how I feel about this. Why make it more difficult to make? Doesn't touch anything else except that? It just turns it into CBT.

It's in the commit name, I believe. The NCR have been building ass-cancerous levels of barbed wire checkerboards.

**Pull request closed without merging**
