### PR TITLE
Followers Love, also recyclers and colormates

### PR DESCRIPTION
**Pull request by Kavrick**
So, the most important thing about this PR is giving followers back their protolathe and circuit printer. I've talked to many people about this, there is room for abuse but I think that's more of an issue of players that can be handled accordingly. Currently followers are very much relegated to "Followers, corpse in your lobby" with not much else to do. Actually being able to develop and print tech for trade will open a massive amount of opportunities, not only for their own faction, but for others. Followers also do not have a good way to get materials, this incentivizes people to mine to bring to the followers for trade.  

On a side note, added colourmates to NCR, Legion and Bighorn, along with recyclers. Recyclers are more of a side thing, they're actually bugged right now and dont properly give materials, the main reason for wanting them is having some sort of method for deleting items. Right now there are only certain items that work in the autolathe, and having massive piles of trash probably isn't the best for server performance either. I always end up with a mountain of bottles after doing chemistry because I cant get rid of them.

### CODE REVIEW

**Comment by Kavrick** [comment]
Just another minor change, added a way to convert mining points into bottlecaps at a 10:1 ratio. Honestly wont be better than mass-selling fruits but will give an option to use points on when you dont need anything else.

**Comment by ThatGuyFromThatPlace** [comment]
This will kill Brotherhood even more, both in terms of Scribe players, and, their ability to trade with other factions

**Comment by Kavrick** [comment]
> This will kill Brotherhood even more, both in terms of Scribe players, and, their ability to trade with other factions

Going to be honest, the enclave is what have killed the brotherhood. The enclave cant trade tech and yet they're doing just fine. Also you might want to stop and think about, "how did we get to the point where the brotherhood are known as the 'tech traders'" It's a complete anthisis of what they're supposed to do.

**Comment by ExoticJazz** [comment]
I would've preferred if the colormates weren't inside faction bases but somewhere neutral, be it in the lootable clothing stores or inside Bighorn.

**Comment by ExoticJazz** [comment]
I'm also against more circuit printers, one faction should have the advantage of owning one, the rest need to either buy/trade with that faction or hope they find the boards they are looking for amongst loot.

**Comment by Kavrick** [comment]
> I would've preferred if the colormates weren't inside faction bases but somewhere neutral, be it in the lootable clothing stores or inside Bighorn.

The main reason why I put them in faction bases was so people could paint gear their faction colours, and on top of that, there is one in bighorn with this PR.



> I'm also against more circuit printers, one faction should have the advantage of owning one, the rest need to either buy/trade with that faction or hope they find the boards they are looking for amongst loot.

I heavily disagree with this. circuit boards are in basically zero loot pools which means the majority of machinery is completely unbuildable. There is such a massive range of machines that can be built, that trying to make them all available it basically impossible. And if we talk about 'you should trade with the faction that has the circuit printer', that's talking about BoS; a faction that really shouldn't be considered the 'tech traders' but simply are because they are the only people who can do it and leverage it. 

I had a length discussion with carl and others about this and I just simply dont understand your distain for circuit printers. As someone who's done science extensively as a scribe I would like to think I have a firm grasp on what can and cannot be obtained via research. Considering basically no fallout servers have ever added additional systems to science, it's basically stuck at the vanilla TG version of research, meaning there is seriously nothing that powerful that can be created with them. Like for example, the most saught after item that you can print is more than likely the plant DNA manipulator, in the grand scheme of things, is that such a broken item?

**Comment by Kavrick** [comment]
I mean honestly if we want to step towards scarcity, I'd be all for it, it'll be a long track because honestly sunset has a lot of abundance. I'd be fine with removing the printer.

**Comment by Kavrick** [comment]
Remove the circuit printer and added some basic boards to make up for it, I hope that's a good middleground.

**Review by ExoticJazz — APPROVED** [review]

**Pull request merged**
