### PR TITLE
Bunker Overhaul Redux (Mapping)

### PR DESCRIPTION
**Pull request by Kavrick**
Based on my previous mapping overhaul, I went through and took feedback.

The surface area has been massively cut down.
There's a single entrance to the bunker, no more magic elevator as per Exotic Jazz's request
Things have been organized and cut down to optimize placement of rooms (Scribes have their own section, knights have their own section, medical is across from research, etc.)
The base has been moved into an underground location that matches it's above ground entrance.

(Also like two fixes to warren, making a flag non-dense and giving the vet ranger's office door a name, as per request from one)

Screenshots to follow
StrongDMM_AjFjx9KHLV
StrongDMM_tYkkiLWJFp

### CODE REVIEW

**Comment by Kavrick** [comment]
Tested as of this commit. Even though it has map conflicts, the one that it conflicts with only changes the BoS area so this should be fine.

https://github.com/sunset-wasteland/sunset-wasteland/pull/454

**Comment by Kavrick** [comment]
Didn't include screenshot of the entrance, so it's here:
StrongDMM_Dy46qXfeco

**Comment by ExoticJazz** [comment]
Will manually merge it in the Bighorn update.

**Comment by ExoticJazz** [comment]
Will need you to send me the .dmms since I can't do a Checkout due to the branch being deleted, need the files so I can merge them manually.

**Comment by ProbablyCarl** [comment]
Any chance of you solving the conflicts? I'll go ahead and merge it afterwards, once done.

**Pull request closed without merging**
