### PR TITLE
THE RECKONING (Removing wound armor, heavy armor keeps 10, PA-level gear gets 20)

### PR DESCRIPTION
**Pull request by Kavrick**
As title, not much more to say, went through armor and removed wound armor. The only thing I kept was helmets having 40 wound armor, so people actually have an incentive to wear their helmets to stop their brains from being painted across the pavement.

### CODE REVIEW

**Comment by Kavrick** [comment]
Oh also buffed combat duster to have the same stats as combat armor and made it so NCR berets had the same stats as NCR trooper helms, as per dragonfruit's request.

**Comment by ExoticJazz** [comment]
> Oh also buffed combat duster to have the same stats as combat armor and made it so NCR berets had the same stats as NCR trooper helms, as per dragonfruit's request.

Why would a beret offer the same protection as a military helmet?

**Comment by Kavrick** [comment]
> > Oh also buffed combat duster to have the same stats as combat armor and made it so NCR berets had the same stats as NCR trooper helms, as per dragonfruit's request.
> 
> Why would a beret offer the same protection as a military helmet?

This was all done while in voice chat with carl, he gave me the green light to do this.

The beret thing is just something dragonfruits requested, if we want to talk about "why does x have so much armor", we have a lot of inconsistencies like that anyway, like the NCR Labcoat having 50 bullet armor when it's a medical labcoat, I think someone wanting to wear a beret and not particularly being punished for it is fine imo, especially when it's still uniform.

**Review by ProbablyCarl — APPROVED** [review]

**Comment by UntoldTactics** [comment]
I'd argue for the rarer versions of PA (t-60 and enclave power armor etc, maybe excavator?) having slightly better wound resistances than prior versions, though that's just a opinion and not really because of balance, just makes some sense in my smol head.

**Pull request merged**
