### PR TITLE
Temporary Parrying removal

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request
Comments out parrying from the code.

## Why It's Good For The Game
120-300 damage from parrying is a hilarious trip. Thats through armor.
Realized what was happening after extensive testing on it in the thunderdome.
Disabling it until someone can fix it, so it's not horrendously broken.

## Pre-Merge Checklist

- [X ] You tested this on a local server.
- [X ] This code did not runtime during testing.
- [X ] You documented all of your changes.

## Changelog

:cl:
del: Comments out parrying
/:cl:

### CODE REVIEW

**Comment by Nep993** [comment]
smh that's a mess of a PR rynn

**Comment by RadiantFlash7** [comment]
> smh that's a mess of a PR rynn

I forgot to delete my last fork and worked on the old branch.
feel free to do the change yourself if you want. I'm supposed to be writing an essay here.

**Comment by HissyNays** [comment]
I agree it needs to have damage modifier toned down. But fuck disabling, parrying is too much fun to disable, a big disapproval from me on this

**Comment by Spc-Dragonfruits** [comment]
#685

**Pull request closed without merging**
