### PR TITLE
Updates Outlaw Gangtool

### PR DESCRIPTION
**Pull request by hackerjsimon**
## About The Pull Request
-Balances the price of items to match wasteland a bit better, and prices will allow outlaws who've joined late to reasonably afford items.
-Adds a new & expensive bundle called 'Big Boss' costing 1200 caps containing: a Salvaged Raider PA kit, Winchester shotgun(with generic ammo), and two drugs because of filler.

## Why It's Good For The Game
Adds a small piece of content to an outdated piece of the game, as well as includes actually decent prices in the outlaw gang tool.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: New Bundle
tweak: Changed some prices to be reasonable.
/:cl:

### CODE REVIEW

**Comment by hackerjsimon** [comment]
IMPORTANT THAT THESE TWO ARE MERGED TOGETHER:
https://github.com/sunset-wasteland/sunset-wasteland/pull/187

**Comment by ExoticJazz** [comment]
Not merging until you resolve the checks.
image

**Comment by AddressUnknown1** [comment]
LIAR

**Comment by hackerjsimon** [comment]
Will work on this in a hour

**Pull request closed without merging**
